apiVersion: v1
kind: ConfigMap
metadata: { name: app-config, namespace: devops-mini }
data:
  APP_MESSAGE: "Hello from Flask on K8s!"
---
apiVersion: v1
kind: Secret
metadata: { name: app-secret, namespace: devops-mini }
type: Opaque
stringData:
  APP_MODE: "prod"
