# k8s/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-deployer
  namespace: devops-mini
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer
  namespace: devops-mini
rules:
  - apiGroups: ["","apps","batch"]
    resources: ["pods","services","deployments","replicasets","configmaps"]
    verbs: ["get","list","watch","create","update","patch"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-binding
  namespace: devops-mini
subjects:
  - kind: ServiceAccount
    name: jenkins-deployer
    namespace: devops-mini
roleRef:
  kind: Role
  name: deployer
  apiGroup: rbac.authorization.k8s.io

